spring:
  datasource: 
    url: jdbc:postgresql://localhost:5432/shop
    username: macmini
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      generate-ddl: true
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database_platform: org.hibernate.dialect.PostgreSQLDialect